"""initial DB migration

Revision ID: f60753ec3d29
Revises:
Create Date: 2025-03-07 18:54:43.756278

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f60753ec3d29"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
